github:
  release: true
npm:
  publish: false
  ignoreVersion: true
git:
  requireCleanWorkingDir: false
  tagName: "v${version}"
  addUntrackedFiles: true
hooks:
  "after:bump": 
    - "cat scripts/master.sh | sed \"s/VERSION=/VERSION=${version}/g\" > ./offering.sh; chmod +x ./offering.sh; cp scripts/master.json ./offering.json"
