# This is a basic workflow to help you get started with Actions

name: CI For Cloud-Native Toolkit Private Catalog

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  repository_dispatch:
    types: [opened, deleted]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: node:12-stretch

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Clone iZero
      uses: actions/checkout@v2
      with:
        repository: ibm-garage-cloud/ibm-garage-iteration-zero
        path: clone

    # Runs a single command using the runners shell
    - name: Build Source
      run: |
        ./scripts/build.sh

      # Runs a single command using the runners shell
    - name: Publish
      run: ./scripts/publish.sh
